code-server (1.91.1, biol1435.jupyter.brown.edu, server-distro)
Jupyter Extension Version: 2024.6.0.
Python Extension Version: 2024.14.1.
Pylance Extension not installed.
Platform: linux (x64).
Workspace folder /home/jovyan, Home = /home/jovyan
10:57:34.944 [info] Starting Kernel (Python Path: /opt/conda/envs/biol1435/bin/python, Conda, 3.9.21) for '~/ps1-updated.ipynb' (disableUI=true)
10:57:34.948 [info] Starting Kernel (Python Path: /opt/conda/envs/biol1435/bin/python, Conda, 3.9.21) for '~/in class/diversity_and_variation.ipynb' (disableUI=true)
10:57:42.114 [info] Process Execution: /opt/conda/envs/biol1435/bin/python -m pip list
10:57:42.169 [info] Process Execution: /opt/conda/envs/biol1435/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:57:42.178 [info] Process Execution: /opt/conda/envs/biol1435/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v2-54494rgN94ylLoI7x.json
    > cwd: //home/~/in class
10:57:42.306 [info] Process Execution: /opt/conda/envs/biol1435/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:57:42.313 [info] Process Execution: /opt/conda/envs/biol1435/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v2-544942dtj228Ft7dX.json
    > cwd: //home/~
10:57:43.040 [info] Kernel successfully started
10:57:43.275 [info] Kernel successfully started
14:07:32.825 [info] Dispose Kernel '~/ps1-updated.ipynb' associated with '~/ps1-updated.ipynb'
14:07:32.833 [info] Dispose Kernel '~/in class/diversity_and_variation.ipynb' associated with '~/in class/diversity_and_variation.ipynb'
14:07:32.870 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v2-54494rgN94ylLoI7x.json for pid 58797 [Canceled (FileSystemError): Canceled
	at P.e (/opt/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:153:7234)
	at Object.stat (/opt/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:153:3900)
	at async Wc.delete (/home/~/.local/share/code-server/extensions/ms-toolsai.jupyter-2024.6.0-universal/dist/extension.node.js:239:15722)
	at async /home/~/.local/share/code-server/extensions/ms-toolsai.jupyter-2024.6.0-universal/dist/extension.node.js:303:469] {
  code: 'Unknown'
}
14:07:32.873 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v2-544942dtj228Ft7dX.json for pid 58799 [Canceled (FileSystemError): Canceled
	at P.e (/opt/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:153:7234)
	at Object.stat (/opt/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:153:3900)
	at async Wc.delete (/home/~/.local/share/code-server/extensions/ms-toolsai.jupyter-2024.6.0-universal/dist/extension.node.js:239:15722)
	at async /home/~/.local/share/code-server/extensions/ms-toolsai.jupyter-2024.6.0-universal/dist/extension.node.js:303:469] {
  code: 'Unknown'
}
